[package]
name = "doom-rust"
version = "0.1.0"
edition = "2024"

[profile.dev]
opt-level = 3
debug = false

[dependencies]
raylib = { version = "6.0.0", features = [
    "SUPPORT_IMAGE_GENERATION",
    "SUPPORT_FILEFORMAT_BMP",
    "SUPPORT_FILEFORMAT_PNG",
    "SUPPORT_FILEFORMAT_JPG",
    "SUPPORT_FILEFORMAT_MP3",
    "SUPPORT_FILEFORMAT_WAV",
    "SUPPORT_FILEFORMAT_OGG",
] }


